"""
First-run setup system for yt-jellyfin.

Handles:
- Detecting whether the app needs first-run configuration
- Querying the Jellyfin API to discover library folders
- Writing the .env file with user-provided configuration
- Validating paths before saving

Two configuration paths are supported:
  A) Import from Jellyfin — queries Jellyfin's local API for library folders
  B) Manual             — user types paths directly

The Jellyfin API key can be found at:
  <jellyfin-url>/web/index.html#!/apikeys.html
"""
import os
import logging
import urllib.request
import urllib.error
import json

log = logging.getLogger(__name__)

# The working directory of the app — where .env lives
INSTALL_DIR = os.path.dirname(os.path.abspath(__file__))
ENV_PATH    = os.path.join(INSTALL_DIR, ".env")


# ── setup state ────────────────────────────────────────────────────────────────

def is_setup_complete() -> bool:
    """
    Returns True if the minimum required config is present and valid.
    Checks the environment (which includes any loaded .env values).
    """
    library_root = os.environ.get("LIBRARY_ROOT", "").strip()
    db_path      = os.environ.get("DB_PATH", "").strip()
    return bool(library_root and db_path and os.path.isdir(library_root))


# ── Jellyfin API ───────────────────────────────────────────────────────────────

def query_jellyfin_libraries(jellyfin_url: str, api_key: str) -> list[dict]:
    """
    Query the Jellyfin API for configured media library folders.

    Returns a list of dicts:
        { name, path, type }

    Returns empty list on any error — caller handles messaging.

    Jellyfin API key location:
        <jellyfin_url>/web/index.html#!/apikeys.html
    """
    url = jellyfin_url.rstrip("/") + "/Library/VirtualFolders"
    headers = {
        "X-Emby-Token": api_key,
        "Accept":        "application/json",
    }

    try:
        req = urllib.request.Request(url, headers=headers)
        with urllib.request.urlopen(req, timeout=8) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        if e.code == 401:
            raise ValueError("Invalid API key — check your Jellyfin API key and try again.")
        raise ValueError(f"Jellyfin returned HTTP {e.code}. Is the URL correct?")
    except urllib.error.URLError as e:
        raise ValueError(f"Could not reach Jellyfin at {jellyfin_url}. Check the URL and that Jellyfin is running.")
    except Exception as e:
        raise ValueError(f"Unexpected error querying Jellyfin: {e}")

    libraries = []
    for folder in data:
        name      = folder.get("Name", "")
        lib_type  = folder.get("CollectionType", "unknown")
        locations = folder.get("Locations", [])
        for path in locations:
            libraries.append({
                "name":  name,
                "path":  path,
                "type":  lib_type,
            })

    return libraries


# ── .env writer ────────────────────────────────────────────────────────────────

def write_env(library_root: str, db_path: str,
              host: str = "0.0.0.0", port: str = "5000",
              jellyfin_url: str = "", jellyfin_api_key: str = "") -> dict:
    """
    Validate and write configuration to .env.

    Returns { ok, message, error }.
    """
    library_root = library_root.strip()
    db_path      = db_path.strip()

    # Validate
    if not library_root:
        return {"ok": False, "error": "LIBRARY_ROOT is required."}
    if not db_path:
        return {"ok": False, "error": "DB_PATH is required."}
    if not os.path.isdir(library_root):
        return {
            "ok":    False,
            "error": f"LIBRARY_ROOT does not exist or is not a directory: {library_root}\n"
                     f"Check that the path is correct and the drive is mounted.",
        }

    # Ensure DB parent directory exists (app will create the file itself)
    db_dir = os.path.dirname(db_path)
    if db_dir and not os.path.isdir(db_dir):
        try:
            os.makedirs(db_dir, exist_ok=True)
        except OSError as e:
            return {"ok": False, "error": f"Could not create DB directory {db_dir}: {e}"}

    # Write .env
    lines = [
        "# yt-jellyfin configuration",
        "# Generated by the setup wizard. Edit manually if needed.",
        "",
        f"LIBRARY_ROOT={library_root}",
        f"DB_PATH={db_path}",
        f"HOST={host or '0.0.0.0'}",
        f"PORT={port or '5000'}",
    ]
    if jellyfin_url:
        lines += ["", f"JELLYFIN_URL={jellyfin_url}"]
    if jellyfin_api_key:
        lines += [f"JELLYFIN_API_KEY={jellyfin_api_key}"]

    try:
        with open(ENV_PATH, "w") as f:
            f.write("\n".join(lines) + "\n")
        log.info("Configuration written to %s", ENV_PATH)
    except OSError as e:
        return {"ok": False, "error": f"Could not write .env file: {e}"}

    # Apply to current process environment so the app picks it up
    os.environ["LIBRARY_ROOT"] = library_root
    os.environ["DB_PATH"]      = db_path
    os.environ["HOST"]         = host or "0.0.0.0"
    os.environ["PORT"]         = port or "5000"

    return {
        "ok":      True,
        "message": (
            "Configuration saved successfully.\n\n"
            "Please restart the service to activate:\n\n"
            "    sudo systemctl restart yt-jellyfin"
        ),
    }
